Flowpack:
  JobQueue:
    Common:
      # if defined, all queues are prefixed with the configured "queueNamePrefix". This helps if multiple
      # Flow instances share the same queue service.
      queueNamePrefix: ''
      queues: []
#        example:
#          className: 'Flownative\JobQueue\Sqlite\Queue\SqliteQueue'
#          options:
#            storageFolder: "/tmp/"
