Flowpack:
  JobQueue:
    Common:
      presets:
        'default':
          className: 'Flownative\JobQueue\Sqlite\Queue\SqliteQueue'
          # if defined, all queues are prefixed with the configured "queueNamePrefix". This helps if multiple
          # Flow instances share the same queue service.
          queueNamePrefix: ''
          options:
            'foo': 'bar'
          releaseOptions:
            delay: 300
          maximumNumberOfReleases: 3
      queues: []
#        'example':
#          preset: 'default'
#          options:
#            overridden: 'option'
